# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Facts' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Facts

  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry'
  pod 'JSONModel'
  pod 'Haneke', '~> 1.0'

  target 'FactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
